Feature/deeplinking
totorototo/strava pull request #11
Opened 2017-02-21 19:51 UTC by totorototo

work in progress. do not merge right now! 
Authenticate saga not finished yet. @guijesuis

2017-02-21 19:59 UTC, guijesuis requested changes

2017-02-21 19:59 UTC, guijesuis commented on app/deeplink.js
> +      const tokenRegexp = /(?:&code=)(\w*)/g;
no!!!

2017-02-21 19:59 UTC, guijesuis commented on app/deeplink.js
> +      const tokenRegexp = /(?:&code=)(\w*)/g;
we should parse query -> no specific here

2017-02-21 20:01 UTC, totorototo commented on app/deeplink.js
> +      const tokenRegexp = /(?:&code=)(\w*)/g;
got your point!

2017-02-21 21:57 UTC, totorototo commented
changes done! to be merged after being reviewed.

2017-02-22 17:56 UTC, totorototo commented
waiting your approval, Rick!

2017-02-23 12:57 UTC, merged