Feature/oauth2
totorototo/strava pull request #2
Opened 2017-02-04 18:35 UTC by totorototo

@guijesuis cadeau!

2017-02-04 20:20 UTC, guijesuis requested changes
Plz do some changes in your code

2017-02-04 20:20 UTC, guijesuis commented on app/components/login/Login.js
> +            if (event.url.indexOf('strava://localhost') === -1) {
use a ref callBack https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute

2017-02-04 20:20 UTC, guijesuis commented on app/components/login/Login.js
> +                ref={WEBVIEW_REF}
https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute

2017-02-04 20:20 UTC, guijesuis commented on app/helpers/api.js
> +export const callApi = ({endpoint, headers, body}) => {
may be add a settable default request

2017-02-04 20:20 UTC, guijesuis commented on app/helpers/api.js
> +export const callApi = ({endpoint, headers, body}) => {
rename callJSONApi ?

2017-02-04 20:20 UTC, guijesuis commented on app/index.js
> +import * as login from './actions/login'
no import * (can't be staticly analysed for lighter js )

2017-02-04 20:20 UTC, guijesuis commented on app/reducers/athlete.js
> +import * as types from './../constants/actionTypes'
no import *

2017-02-04 20:20 UTC, guijesuis commented on app/reducers/login.js
> +import * as types from './../constants/actionTypes'
same here

2017-02-04 20:20 UTC, guijesuis commented on app/sagas/index.js
>  import * as authentication from './login'
and here again

2017-02-04 20:20 UTC, guijesuis commented on app/services/login.js
> +
and here again

2017-02-04 20:20 UTC, guijesuis commented on app/index.js
> +import{Linking} from 'react-native';
u need coherent spacing, set it up correctely plz, if not automated, automate it

2017-02-04 20:20 UTC, guijesuis commented on app/sagas/login.js
> +    catch (error) {
dosomething here don't silently catch errors -> bad practice -> u will forget it, may be

2017-02-04 20:20 UTC, guijesuis commented on app/services/login.js
> +
may be a helper to build header?

2017-02-04 20:20 UTC, guijesuis commented on package.json
> +    "react-navigation": "^1.0.0-beta.1",
is it better than react router V4 ? what do you think?

2017-02-05 10:08 UTC, totorototo commented on app/index.js
> +import{Linking} from 'react-native';
rules will be set asap.

2017-02-05 11:39 UTC, guijesuis approved these changes

2017-02-05 11:39 UTC, merged